### ISSUE TITLE
[CHORE] 디자인 기초 작업

### ISSUE THREAD

**Issue by bohemio1234** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoriseS2#12]
## 🐲 Description

디자인 기초 작업 하겠습니다.

## 🧑‍💻 Todo

- [x]  폰트(Pretendard, Shantell Sans) 추가 
- [x]  폰트 helper 추가
- [x]  컬러 익스텐션 추가
- [x]  디자인에 필요한 Assets들 (App logo, Image, etc.)

## ✏️ ETC

시네필 등판.
