### ISSUE TITLE
[FEAT] FriendListView

### ISSUE THREAD

**Issue by cho2-0923** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoriseS2#13]
## 🐲 Description
FriendListView를 만듭니다.
Searchbar, Title, Category, FriendGridView, FriendCellView, ShapeCustomView로 나누어 제작하려고 합니다.

## 🧑‍💻 Todo

- [ ]  비정형화된 도형들 구현하기
- [ ] 각각의 요소들 만들기
- [ ] 만든 요소 합치기

## ✏️ ETC

저요! 제가해볼게요!

**Comment by cho2-0923** [comment]
이 이슈 샤따닫슈
