### ISSUE TITLE
[FEAT] CollageByMyselfView 기능 전체 구현 

### ISSUE THREAD

**Issue by teabag759** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoriseS2#23]
## 🐲 Description

<strike>- _RemoveImageBackground를 Sheet 형태가 아닌 Viewmodel로 리팩토링하고, UX를 개선합니다._</strike>

- CollageByMyselfView의 기능을 전체적으로 구현합니다. 

## 🧑‍💻 Todo

<strike>_RemoveImageBackground Viewmodel로 리팩토링하기
UI View 상으로 배경이 제거된 이미지가 나타나도록 처리하기_</strike>

- [ ] 이미지를 잡으면 시트가 자동으로 내려갔다가, 이미지를 놓으면 자동으로 올라가게 하기
- [x] 자동 이미지 캡쳐 구현 
- [x] Alert 후 share 화면 나타나게 띄우기  

## ✏️ ETC

<strike>_ViewModel로 만들면 UIView 로 나타나는 게 반영이 되지 않고 있습니다._ </strike>

CollageByMyselfView 에 나타난 전체적인 기능을 구현한 후 View를 연결하고자 합니다.
