### ISSUE TITLE
[FEAT] CollageByMyselfView 기능 및 코드 정리

### ISSUE THREAD

**Issue by teabag759** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoriseS2#33]
## 🐲 Description

CollageByMyselfView 에서 나타나는 부자연스러운 동작들을 수정하고 코드를 깔끔하게 정리하고자 합니다. 

## 🧑‍💻 Todo

- [ ]  capture시 EditView 크기 만큼 자르기 
- [ ] 사진 배경 제거시 배경이 제거된 피사체만큼 크기 수정하기 
- [ ] CustomSheet 애니메이션 수정하기 
- [ ] 전체적으로 자연스럽게 동작하도록 만들기 

## ✏️ ETC

이것만 얼추하면 진짜 출시할 수 있지 않을까요
