### ISSUE TITLE
[FEAT] 메모기능/콜라주뷰에서 친구 디테일 뷰로 연결+이름 수정(기존 임찬우)+사진 수정이 아닌 추가되는 오류 고치기

### ISSUE THREAD

**Issue by hajizn-pi** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoriseS2#35]
## 🐲 Description

메모기능추가
콜라주뷰에서 친구 디테일 뷰로 연결
콜라주 뷰 이름 수정(기존 임찬우)

## 🧑‍💻 Todo

- [x] 메모기능추가
- [x] 콜라주뷰에서 친구 디테일 뷰로 연결
- [x] 콜라주 뷰 이름 수정(기존 임찬우)
- [x] 사진 수정이 아닌 추가되는 오류 수정

## ✏️ ETC
지긋지긋한 브랜치 22번에서 벗어났습니다 진짜 너무 힘들었어요...
